config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :mixes
  resources :users
  resources :sessions
  
  get '/main' => 'users#index'
  

  root 'welcome#index'

end

app/models/mix.rb
class Mix < ActiveRecord::Base
	validates :title, presence: true,
	length: { minimum: 1 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	#validates_presence_of :username, :password
	#validates :password, confirmation: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    users_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController

	def index
		@mixes = Mix.all 
	end

	def show
		@mixes = Mix.find(params[:id])
	end

	def new
		@mixes = Mix.new
	end

	def edit
		@mixes = Mix.find(params[:id])
	end

	def create
		@mixes = Mix.new(mixes_params)

		if @mixes.save
			redirect_to @mixes
		else
			render 'new'
		end
	end

	def update
		@mixes = Mix.find(params[:id])
		if @mixes.update(mixes_params)
		redirect_to @mixes
	else
		render 'edit'
	end
end

def destroy
	@mixes = Mix.find(params[:id])
	@mixes.destroy

	redirect_to mixes_path
end

	private
	def mixes_params
		params.require(:mix).permit(:title, :text)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    flash[:alert] = "Successfully Logged Out"
    redirect_to root_path
  end

  def create
    username = params[:username]
    password = params[:password]

    @user = User.where(username: username).first

    if @user.nil?
      #wrong username case
      flash[:alert] = "Incorrect credentials"
      redirect_to root_path
    else
      if @user.password == password
        session[:user_id] = @user.id
        flash[:alert] = "Welcome!"
        redirect_to mix_path
      else
        #wrong password case
        flash[:alert] = "Incorrect credentials"
        redirect_to root_path
      end
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])	
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mixes_helper.rb
module MixesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="wroy.css">
  <title>WROY-BDM</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div id="header">

    <%= yield %>
</div>
 <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
</body>
</html>

app/views/mixes/_form.html.erb
<%= form_for @mixes do |f| %>
	<% if @mixes.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@mixes.errors.count, "error") %>
				prohibited
				this mix from being saved:
			</h2>
			<ul>
				<% @mixes.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
<% end %>
		<p>
			<%= f.label :title %><br>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :text %><br>
			<%= f.text_area :text %>
		</p>

		<p>
			<%= f.submit %>
		</p>

		<% end %>

app/views/mixes/edit.html.erb
<h1>Editing Mix</h1>

<%= render 'form' %>

	<%= link_to 'Back', mixes_path %>

app/views/mixes/index.html.erb
<h1>List of Mixes</h1>
<br>
<%= link_to 'New Mix', new_mix_path %>

<table>
	<tr>
		<th>Title</th>
		<th>Description</th>
		<th colspan="2"></th>
	</tr>

	<% @mixes.each do |mix| %>
	<tr>
		<td><%= mix.title %></td>
		<td><%= mix.text %></td>
		<td><%= link_to 'Show', mix_path(mix) %></td>
		<td><%= link_to 'Edit', edit_mix_path(mix) %></td>
		<td><%= link_to 'Delete', mix_path(mix),
						method: :delete,
						data: {confirm: 'Are you sure?'} %>
		</td>
	</tr>
	<% end %>
</table>
<br>
<%= link_to 'Home', controller: 'users' %>

app/views/mixes/new.html.erb
<h1>New Mix</h1>
<%= render 'form' %>

<%= link_to 'Back', mixes_path %>

app/views/mixes/show.html.erb
<p>
	<strong>Name:</strong>
	<%= @mixes.title %>
</p>

<p>
	<strong>URL:</strong>
	<%= @mixes.text %>	
</p>


<%= link_to 'Edit', edit_mix_path(@mixes) %> |
<%= link_to 'Back', controller: 'mixes' %>
<%= link_to 'Home', controller: 'welcome' %>

app/views/users/index.html.erb
<h1>User Index</h1>
<% @users.each do |user| %>
	<p>
		<%= user.fname %>
		<%= user.lname %>
		<%= user.username %>
	</p>
<% end %>

<%= link_to 'List of Mixes', mixes_path %>
<%= link_to 'Sign Out', 'sessions#destroy' %>

app/views/users/show.html.erb
<%= @user.fname %>

app/views/welcome/index.html.erb
<h1>Login</h1>
<br>
  <%= form_tag new_user_session_path do %>
    <%= label_tag "Login:" %>
    <br>
    <%= text_field_tag :email, nil, placeholder: "Email" %>
    <br>
    <%= password_field_tag :password, nil, placeholder: "Password" %>
    <br>
    <%= submit_tag "Log In" %>
  <% end %>


<% if flash[:alert] %>
  <div style="background:yellow;">
    <%= flash[:alert] %>
  </div>
<% end %>

<br><br><br>


 <%= form_for @user do |f| %>
  <%=f.label "Sign Up Here" %>
  <br>
  <%= f.text_field :fname, placeholder: "First Name" %>
  <br>
  <%=f.text_field :lname, placeholder: "Last Name"  %>
  <br>
  <%=f.text_field :username, placeholder: "Username"  %>
  <br>
  <%=f.text_field :email, placeholder: "email" %>
  <br>
  <%=f.password_field :password, placeholder: "Password"  %>
  <br>

  <%=f.submit :"Sign Up" %>
<% end %>